---
# tasks file for roles/Ubuntu/ELK

 - name: Download prerequisite
   apt:
     name:
       - python3
       - python3-pip
     state: latest
     update_cache: yes

 - name: Install Docker
   apt:
     name: docker.io
     state: latest
     update_cache: yes

 - name: Install docker_py
   pip:
     name: docker.py
     state: latest

 - name: Start Docker service
   service:
     name: docker
     state: started
     enabled: yes

 - name: Create docker network
   docker_network:
     name: elastic

 - name: Start elasticsearch container
   docker_container:
     name: elasticsearch
     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
     state: present
     ports:
       - "9200:9200"
       - "9300:9300"
     env:
       discovery.type: "single-node"
     networks:
       - name: elastic

 - name: Download Kibana container
   docker_container:
     name: kibana
     image: docker.elastic.co/kibana/kibana:7.10.1
     state: present
     ports:
       - "5601:5601"
     networks:
       - name: elastic

 - name: Download logstash container
   docker_container:
     name: logstash
     image: docker.elastic.co/logstash/logstash:7.10.1
     state: present
     ports:
       - "5044:5044"
     networks:
       - name: elastic










     
