---
# tasks file for roles/openSUSE/VSFTPD
 
 - name: Install vsftpd service
   become: yes
   zypper:
     name: vsftpd
     state: latest
     update_cache: yes

 - name: Disable firewall
   become: yes
   service:
     name: firewalld
     state: stopped
     enabled: no

 - name: Start vsftpd service
   become: yes
   service:
     name: vsftpd
     state: started
     enabled: yes

 - name: Create ftp user
   user:
     name: '{{ ftp_user }}'
     password: '{{ ftp_pass }}'

 - name: Add DenyUsers
   lineinfile:
     path: /etc/ssh/sshd_config
     line: "DenyUsers '{{ ftp_user }}'"
   register: sshd_config

 - name: Restart sshd service
   service:
     name: sshd
     state: restarted
   when: sshd_config.changed

 - name: Copy vsftpd.conf
   copy:
     src: /etc/vsftpd.conf
     dest: /etc/vsftpd.conf.default
     remote_src: true

 - name: Restart vsftpd
   service:
     name: vsftpd
     state: restarted

