---
# tasks file for roles/CentOS/Lampstack
 - name: Install httpd
   dnf:
     name: httpd
     state: latest

 - name: Start httpd service
   service:
     name: httpd
     state: started

 - name: Allow firewall
   firewalld:
     service: http
     permanent: yes
     state: enabled

 - name: Install MariaDB
   dnf:
     name:
       - mariadb-server
       - mariadb
     state: present

 - name: Start mariadb service
   service:
     name: mariadb
     state: started
     enabled: yes

 - name: PHP
   dnf:
     name:
       - php 
       - php-mysqlnd  
       - php-gd 
       - php-xml 
     state: latest

 - name: Restart httpd
   service:
     name: httpd
     state: restarted



