---
 - name: Install vsftpd
   become: yes
   apt:
     name: vsftpd
     state: latest
     update_cache: yes

 - name: Configure firewall
   become: yes
   service:
     name: ufw
     state: stopped
     enabled: no
 
 - name: Create a FTP user
   become: yes
   user:
     name: sam
     comment: user_sam
     password: $5$RlO6JqXc0gi52n1k$YSl7ciEf0Ae0NECVAmGN6pspwG7uEiuUEtrp3d/hRlC

 - name: Denying ftp user
   become: yes
   lineinfile:
     path: /etc/ssh/sshd_config
     line: "DenyUsers sam"
   register: sshd_config

 - name: Restart SSHD service
   become: yes
   service:
     name: sshd
     state: restarted
   when: sshd_config.changed

 - name: Create FTP directory
   become: yes
   file:
     path: ~/samuel/ftp
     state: directory
     owner: nobody
     group: nogroup
     mode: '0555'

 - name: Create files folder in FTP directory
   become: yes
   file:
     path: ~/samuel/ftp/files
     state: directory
     owner: samuel
     group: samuel

 - name: Copy vsftpd.conf file
   become: yes
   copy:
     src: vsftpd.conf
     dest: /etc/vsftpd.conf
   register: vsftpd_modified

 - name: Restart vsftpd.conf
   become: yes
   service:
     name: vsftpd
     state: restarted
   when: vsftpd_modified.changed

    




# tasks file for roles/Ubuntu_Install
