---
# tasks file for roles/Ubuntu/Lampstack
 - name: Install apache2
   apt:
     name:
       - apache2
       - apache2-utils
     state: latest

 - name: allow HTTP
   ufw:
     rule: allow
     direction: in
     name: Apache

 - name: Install MariaDB
   apt:
     name:
       - mariadb-server
     state: latest

 - name: Install php
   apt:
     name: php7.4
     state: latest

 - name: Install php module
   apt:
     name:
       - libapache2-mod-php
       - php-mysql




