---
# tasks file for roles/CentOS/ELK
 - name: Install java
   yum:
     name: java-1.8.0-openjdk
     state: present

 - name: Add elastic key
   command: sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

 - name: Add elastic repo
   copy:
     src: Repo_files/elasticsearch.repo
     dest: /etc/yum.repos.d/

 - name: Update cache
   dnf:
     update_cache: yes

 - name: Install elasticsearch
   dnf:
     name: elasticsearch
     state: present

 - name: Uncomment http port
   replace:
     path: /etc/elasticsearch/elasticsearch.yml
     regexp: '#http.port: 9200'
     replace: 'http.port: 9200'

 - name: Uncomment network host
   replace:
     path: /etc/elasticsearch/elasticsearch.yml
     regexp: '#network.host '
     replace: 'network.host: localhost'

 - name: Install Kibana
   dnf:
     name: kibana  
     state: present

 - name: Uncomment server port
   replace:
     path: /etc/kibana/kibana.yml
     regexp: '#server.port: 5601'
     replace: 'server.port: 5601'

 - name: Uncomment localhost   
   replace:
     path: /etc/kibana/kibana.yml
     regexp: '#elasticsearch.host: ["http://localhost:9200"]'
     replace: 'elasticsearch.host: ["http://localhost:9200"]'

 - name: Reload service
   command: firewall-cmd --reload

 - name: Install logstash
   dnf:
     name: logstash
     update_cache: yes

 - name: Configure logstash
   copy:
     src: Repo_files/logstash.conf
     dest: /etc/logstash/conf.d/

 - name: Starting service
   service:
     name: elasticsearch
     state: started
     enabled: yes

 - name: Start kibana service
   service:
     name: kibana
     state: started
     enabled: yes

 - name: Start logstash service
   service:
     name: logstash
     state: started
     enabled: yes



